"""no-op check for leave relationship

Revision ID: 344c4e61aac3
Revises: eccc0b1e4337
Create Date: 2026-09-05 23:11:24.938799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '344c4e61aac3'
down_revision: Union[str, Sequence[str], None] = 'eccc0b1e4337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
