"""add payslip period uniqueness and employee relationship

Revision ID: 34ccdbb08d13
Revises: 344c4e61aac3
Create Date: 2026-09-05 23:41:18.952693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34ccdbb08d13'
down_revision: Union[str, Sequence[str], None] = '344c4e61aac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_employee_payslip_period', 'payslips', ['employee_id', 'month', 'year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_employee_payslip_period', 'payslips', type_='unique')
    # ### end Alembic commands ###
