"""add organization settings table

Revision ID: 6ff38863a92f
Revises: 34ccdbb08d13
Create Date: 2026-09-06 00:01:29.663902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff38863a92f'
down_revision: Union[str, Sequence[str], None] = '34ccdbb08d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('late_cutoff_hour', sa.Integer(), nullable=False),
    sa.Column('late_cutoff_minute', sa.Integer(), nullable=False),
    sa.Column('annual_leave_days', sa.Integer(), nullable=False),
    sa.Column('casual_leave_days', sa.Integer(), nullable=False),
    sa.Column('sick_leave_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_settings')
    # ### end Alembic commands ###
