"""rename date to attendance_date

Revision ID: e5775e8ec2d4
Revises: 2c56f0bd05d3
Create Date: 2026-09-05 19:47:12.143942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5775e8ec2d4'
down_revision: Union[str, Sequence[str], None] = '2c56f0bd05d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('attendance_date', sa.Date(), nullable=False))
    op.drop_column('attendance', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('attendance', 'attendance_date')
    # ### end Alembic commands ###
