"""add unique constraint on employee attendance date

Revision ID: f51553645af6
Revises: dd325b82467a
Create Date: 2026-09-05 21:33:18.987239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f51553645af6'
down_revision: Union[str, Sequence[str], None] = 'dd325b82467a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_employee_attendance_date', 'attendance', ['employee_id', 'attendance_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_employee_attendance_date', 'attendance', type_='unique')
    # ### end Alembic commands ###
