"""editted model for attendance to have employe bio details embedded

Revision ID: fc0ffdbbdfda
Revises: 3a8aa92518d2
Create Date: 2026-09-06 20:38:40.607024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0ffdbbdfda'
down_revision: Union[str, Sequence[str], None] = '3a8aa92518d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
